### ISSUE TITLE
Difference between MapForge and MER

### ISSUE THREAD

**Issue by Nekonyx** [Killers0992/MapForge#1]
Hi! I'm curious about the differences between MapForge and [Michal's MapEditorReborn](https://github.com/Michal78900/MapEditorReborn/). Are there any key aspects or features that distinguish them?
Thanks!

**Comment by Killers0992** [comment]
My plugin dont have ingame editing which means you cant edit your map ingame only thru editor, most of stuff is similar to MER but allows for some advanced stuff in case of custom components attached to objects.
